### ISSUE TITLE
Fix lane height and scroll to see the cards

### ISSUE THREAD

**Issue by lourenci** [asseinfo/react-kanban#97]
Today, the lane has the height to fit all the cards in the screen.

What about if we have a prop to change this behaviour? We could support 3 kinds of lanes:
* A lane that fit the screen height and scroll the cards.
* A lane that fit a specified height and scroll the cards.
* The default (today) behaviour.

**Comment by lourenci** [comment]
Today, the lane has the height to fit all the cards in the screen.

What about if we have a prop to change this behaviour? We could support 3 kinds of lanes:
* A lane that fit the screen height and scroll the cards.
* A lane that fit the a specified height and scroll the cards.
* The default (today) behaviour.

**Comment by GLuchtenberg** [comment]
I've a question about this feature...
Seems like you're talking about the board, not the lane, is that correct?

**Comment by lourenci** [comment]
Hi, @GLuchtenberg. Yes, this behaviour is for all the lanes, thus to the board.

**Comment by GLuchtenberg** [comment]
For me, it seems like the kanban board should always fit the container height... Have props to add behaviour on height seems like having more responsibilities than it should

**Comment by lourenci** [comment]
You've a point.

If the user wants to apply a fixed height to the board, how could it apply the scroll to the lane?

**Comment by GLuchtenberg** [comment]
I'll try to do this in a PR...

I'll probably follow something like add inline-flex to the board and remove lane 100% height so it will try to fill all parent height and if it can't, will add an scroll bar to the lane

**Comment by MaheshKonne** [comment]
Cypress tests are failing, I'm unable to create a PR for this.

**Comment by MaheshKonne** [comment]
@lourenci I'm planning to support these values height:"auto"/"500px". Any suggestions on height props?

**Comment by lourenci** [comment]
Go ahead with that.

**Comment by MaheshKonne** [comment]
@lourenci I've updated the PR with height props.

**Comment by mathesouza** [comment]
How is this issue going? @GLuchtenberg

**Comment by acroyear** [comment]
On the beta, the behavior still isn't quite doing what Trello does, where the cards can scroll independently and the header remains 'sticky' at the top.

This code will approach that, though you might have better options for constraining the height (along with column and board).  I haven't quite figured out all the flex-stuff needed to make that work.

```
.react-kanban-column > div:nth-of-type(2) {
  max-height: 500px !important;
  overflow-y: scroll;
}
```

but without that constraint, the whole board is the height of the longest column and scrolling will scroll all the way down to the bottom of the whole page.

**Comment by cmacdonnacha** [comment]
Hey, any progress on this one?

**Comment by PeteDuncanson** [comment]
I couldn't see an easy way to change the hardcorded styles on the BoardContainer element that the board uses. I wanted my Board to scroll on the X/Y and take up the full available space on my page minus my header (whihc I have some filters etc in ).

Came up with this hack which might help others, put this in the component that calls the Board component and it should sort it for you:

```
  useEffect(() => {
    // Overpower the hardcoded style on the Kanban board to fix the scrolling
    const kanbanElements = window.document.getElementsByClassName("react-kanban-board");
    console.info("Kanban Boards", kanbanElements);
    if (kanbanElements[0] !== undefined) {
      const kanbanBoard = kanbanElements[0] as HTMLElement;
      kanbanBoard.style.height = "calc(100vh - 270px)";
      kanbanBoard.style.overflowY = "scroll";
    }
  }, []);
```
